					<div class="cards" >
						<a href="{{CROOT}}institucional/sobre-a-empresa/" class="card grid-4 height-2 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}institucional/imgs/about.png" alt="[Ícone]" width="96" height="128" />
								<strong class="display-block margin-bottom-small" >Sobre a Empresa</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in felis egestas rutrum.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}institucional/politica-de-privacidade/" class="card grid-4 height-2 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}institucional/imgs/privacity.png" alt="[Ícone]" width="111" height="128" />
								<strong class="display-block margin-bottom-small" >Política de Privacidade</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}institucional/seguranca/" class="card grid-4 height-2 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}institucional/imgs/security.png" alt="[Ícone]" width="105" height="128" />
								<strong class="display-block margin-bottom-small" >Segurança</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in felis egestas rutrum.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}institucional/controle-de-qualidade/" class="card grid-4 height-2 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}institucional/imgs/quality.png" alt="[Ícone]" width="88" height="128" />
								<strong class="display-block margin-bottom-small" >Controle de Qualidade</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}institucional/seja-nosso-fornecedor/" class="card grid-4 height-2 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}institucional/imgs/supplier.png" alt="[Ícone]" width="128" height="112" />
								<strong class="display-block margin-bottom-small" >Seja Nosso Fornecedor</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<div class="clearfix" ></div>
					</div>
