<!DOCTYPE html>
<html lang="en" >
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Senha alterada com sucesso | Cadastro</title>
		{{VIEW:head}}
		<link rel="stylesheet" type="text/css" href="{{CROOT}}{{GT8:account.root}}css/account.css" />
		<script type="text/javascript" src="{{CROOT}}{{GT8:account.root}}js/account.js" ></script>
		<script type="text/javascript" >
		//<![CDATA[
			
		//]]>
		</script>
	</head>
	<body class="account reset-pass-confirm" >
		<div id="eMain" >
			{{VIEW:header}}
			{{VIEW:location}}
			<div class="account row-12 resume fluid-12 clearfix-child" >
				<h1 class="margin-bottom grid-7 prefix-2h suffix-2h" >Senha Alterada</h1>
				<div class="grid-7 prefix-2h suffix-2h clearfix-child" >
					<div class="grid-12 marginless bg-white shadow-small" >
						<div class="padding-large clearfix-child" >
							<h2 class="grid-12" >Sua senha foi alterada com sucesso!</h2>
							<p class="grid-12 clearfix-child" >
								A partir de agora, você poderá acessar seu cadastro com sua nova senha. Lembre-se, sua senha é pessoal e intrasferível. Mantenha-a segura.
							</p>
							
							<div class="height-medium grid" ></div>
							<hr class="grid-12 margin-bottom" />
							<p class="grid-12 clearfix-child margin-bottom-none omega" >
								<a href="../../" class="href-button href-button-blue grid-12 marginless omega line-height-large" >
									<span>Voltar</span>
								</a>
							</p>
						</div>
					</div>
				</div>
			</div>
			{{VIEW:footer}}
		</div>
	</body>
</html>