					<li>
						<a href="{{CROOT}}institucional/sobre-a-empresa/" class="href-button href-button-cancel line-height-large font-size-small text-align-left text-indent margin-bottom-small" >
							<span>Sobre a empresa</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}institucional/politica-de-privacidade/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Política de Privacidade</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}institucional/seguranca/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Segurança</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}institucional/controle-de-qualidade/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Controle de Qualidade</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}institucional/seja-nosso-fornecedor/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Seja Nosso Fornecedor</span>
						</a>
					</li>
