					<h1 class="margin-bottom-none" >Política de Privacidade</h1>
					<div class="margin-bottom-large" ><small>Última atualização: 6 de janeiro de 2013</small></div>
					
					<h3 class="margin-bottom-none" >Informações Pessoais</h3>
					<p>
						As informações pessoais que obtemos através de seu cadastro e sua navegação <strong>nunca</strong> serão vendidas, transferidas ou compartilhadas com terceiros. Elas são utilizadas para lhe proporcionar uma navegação personalizada,
						de acordo com suas preferências.
					</p>
					
					<h3 class="margin-bottom-none" >Cookies</h3>
					<p>
						<em>Cookies</em> são informações armazenadas em seu próprio dispositivo para lembrar suas preferências ao navegar pelo site <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a>. Se o seu navegador estiver com os <em>Cookies</em>
						habilitados, nós usaremos esse recurso para lembrar seus produtos preferidos e preferências de navegação.
					</p>
					
					<h3 class="margin-bottom-none" >E-mail</h3>
					<p>
						Seu e-mail poderá ser usado para contatá-lo sobre sua conta em caso de esquecimento de senha ou de necessidade de ajuda. Se você assinou nossa <em>Newsletter</em>, enviaremos periodicamente, com o seu consentimento, <em>e-mail marketing</em>, podendo este ser cancelado a qualquer momento.
					</p>
					
					<h3 class="margin-bottom-none" >Segurança</h3>
					<p>
						Para proteger sua privacidade e aumentar a segurança, o <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> utiliza encriptografia de 128 bits por meio de soquetes SSL, que encriptam as informações transmitidas e recebidas nas áreas de compras e cadastro.
						Para saber mais, acesse <a href="{{CROOT}}institucional/seguranca/" class="link" >segurança</a>.
					</p>