					<h1>Segurança</h1>
					
					<h3 class="margin-bottom-none" >SSL</h3>
					<p>
						Para protejer sua navegação, a empresa utiliza encriptografia SSL de 128 bits da empresa Comodo Secure (uma das maiores empresas certificadoras do mundo) ao processar informações sensíveis de seu cadastro ou compra.
					</p>
					
					<h3 class="margin-bottom-none" >Senha</h3>
					<p>
						Sua senha é encriptografada antes de ser armazenada em nosso banco de dados, sendo ilegível. Nenhum funcionário tem acesso a ela. Em caso de esquecimento, não é possível recuperar a senha, mas apenas a definição para uma nova senha mediante um procedimento específico, conforme instruções na página <a href="{{CROOT}}{{GT8:account.root}}{{GT8:account.resetPassword.root}}" >redefinicao-de-senha</a>.
					</p>
					
					<h3 class="margin-bottom-none" >Integridade do site</h3>
					<p>
						Para assegurar a integridade do site, um scaner é passado sobre o site regularmente sendo todos os seus arquivos analisados. Todas as modificações, inserções e exclusões são registradas e arquivadas, permitidando que nenhum arquivo seja modificado de forma inadvertida.
					</p>
					
					<h3 class="margin-bottom-none" >Cartões de crédito</h3>
					<p>
						O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> não armazena os dados de seu cartão de crédito. Todas as informações pertinentes às transações do cartão são transferidas diretamenta às operados de crédito.
					</p>