					<h1>Seja Nosso Fornecedor</h1>
					<p>
						Nosso objetivo é oferecer o melhor produto ao consumidor, ganhar sua confiança e respeito. Para isso, sabemos que é importantíssimo um relacionamento próximo e cooperativo com nossos fornececores, para negociar o melhor preço e produto.
					</p>
					<p>
						Seja um parceiro do <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> e construa conosco uma maneira diferenciada de comercializar pela internet.
					</p>
					<p>
						Entre em contato com a central de relacionamento para solicitar uma reunião comercial {{GT8:phone-number}}. Será um prazer atendê-lo.
					</p>