					<h1>Sobre a Empresa</h1>
					<p>
						A empresa <a href="http://www.salaodocalcado.com.br/" class="link" >Salãodocalcado.com.br</a>, com sede em São Paulo, é especializada em calçados femininos nobres, de alta qualidade. A empresa trabalha somente com produtos de primeira linha.
						Todos os seus calçados são em couro legítimo.
					</p>
					<p>
						O serviço de compras online, disponibilizado pelo site <a href="http://www.salaodocalcado.com.br/" class="link" >Salãodocalcado.com.br</a>, proporciona ao cliente uma navegação agradável, limpa, de fácil compreensão e livre de publicidade. O site possui os mais recentes
						recursos tecnológicos, é objetivo e prático.
					</p>
					<p>
						Para o <a href="http://www.salaodocalcado.com.br/" class="link" >Salãodocalcado.com.br</a>, o cliente é prioridade e a empresa procura fornecer o melhor atendimento possível.
					</p>
					<p class="margin-bottom-large" >
						Desejamos que você tenha uma ótima experiência conosco. Em caso de dúvidas ou para auxílio, estamos à disposição.
					</p>
					<p>
						Equipe <a href="http://www.salaodocalcado.com.br/" class="link" >Salãodocalcado.com.br</a>
					</p>