					<div class="cards clearfix-child" >
						<a href="{{CROOT}}institucional/sobre-a-empresa/" class="card grid-4 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding display-block" >
								<img class="display-block margin-center margin-bottom" src="{{CROOT}}institucional/imgs/about.png" alt="[Ícone]" width="96" height="128" />
								<strong class="display-block margin-bottom-small text-align-center" >Sobre a Empresa</strong>
							</span>
						</a>
						<a href="{{CROOT}}institucional/politica-de-privacidade/" class="card grid-4 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding display-block" >
								<img class="display-block margin-center margin-bottom" src="{{CROOT}}institucional/imgs/privacity.png" alt="[Ícone]" width="111" height="128" />
								<strong class="display-block margin-bottom-small text-align-center" >Política de Privacidade</strong>
							</span>
						</a>
						<a href="{{CROOT}}institucional/seguranca/" class="card grid-4 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding display-block" >
								<img class="display-block margin-center margin-bottom" src="{{CROOT}}institucional/imgs/security.png" alt="[Ícone]" width="105" height="128" />
								<strong class="display-block margin-bottom-small text-align-center" >Segurança</strong>
							</span>
						</a>
						<a href="{{CROOT}}institucional/controle-de-qualidade/" class="card grid-4 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden hidden" >
							<span class="padding display-block" >
								<img class="display-block margin-center margin-bottom" src="{{CROOT}}institucional/imgs/quality.png" alt="[Ícone]" width="88" height="128" />
								<strong class="display-block margin-bottom-small text-align-center" >Controle de Qualidade</strong>
							</span>
						</a>
						<a href="{{CROOT}}institucional/seja-nosso-fornecedor/" class="card grid-4 bg-light shadow-small margin-bottom text-decoration-none overflow-hidden" >
							<span class="padding display-block" >
								<img class="display-block margin-center margin-bottom" src="{{CROOT}}institucional/imgs/supplier.png" alt="[Ícone]" width="146" height="128" />
								<strong class="display-block margin-bottom-small text-align-center" >Seja Nosso Fornecedor</strong>
							</span>
						</a>
					</div>
