
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>{{title}}</title>
		<link rel="stylesheet" type="text/css" href="{{CROOT}}css/gt8/gt8.css" />
		<link rel="stylesheet" type="text/css" href="{{AROOT}}css/main.css" />
		<style type="text/css" >
			{{CSSINCLUDE}}
		</style>
		<script type="text/javascript" src="{{CROOT}}jCube/jCube.single.js" ></script>
		<script type="text/javascript" src="{{CROOT}}js/gt8/gt8.js" ></script>
		<script type="text/javascript" src="{{AROOT}}js/main.js" ></script>
		<script type="text/javascript" >
		//<![CDATA[
			{{JSINCLUDE}}
		//]]>
		</script>
		{{scripts}}
		{{css}}
	</head>
