<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Página não encontrada: 404</title>
		{{VIEW:head}}
	</head>
	<body class="not-found" >
		<div id="eMain" >
			{{VIEW:header}}
			<div class="height-superlarge" ></div>
			<div class="row-12 cards" >
				<p class="grid-2" >
					<img src="{{CROOT}}imgs/critical-large.png" alt="[Página não encontrada]" width="128" height="128" />
				</p>
				<h1 class="grid-8" >Desculpe-nos o transtorno,</h1>
				<p class="grid-8" >
					mas não encontramos a página <span class="text-error" >"{{path}}"</span> que você tentou acessar.
				</p>
				<p class="grid-8" >
					Se você digitou o endereço, verifique novamente a ortografia.
				</p>
				<div class="clearfix" ></div>
			</div>
			{{VIEW:footer}}
		</div>
	</body>
</html>