			<div class="height-large" ></div>
			<footer class="main" >
				<div class="shadow-container block top" >
					<div class="header row-12 fluid-12 block clearfix-child" >
						<div class="grid-2h t-grid-2 mobile-hidden" >
							<h6>Formas de Pagamento</h6>
							<div class="bandeirasC" >
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|0,0" alt="[Cartão Master Card]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|1,0" alt="[Cartão Visa]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|2,0" alt="[Cartão American Express]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|0,1" alt="[Cartão Diners Club]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|1,1" alt="[Cartão Paypal]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|2,1" alt="[Boleto Bancário]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|0,2" alt="[Cartão Hipercard]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|1,2" alt="[Cartão American Express]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|2,2" alt="[Transferência Bradesco]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|0,3" alt="[Transferência Itaú]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|1,3" alt="[Transferência Banco do Brasil]" />
								<img src="{{CROOT}}imgs/gt8/blank.gif" class="auto-sprite" title="|{{CROOT}}imgs/sprite-bandeiras.png|50|2,3" alt="[Diners Club]" />
							</div>
						</div>
						<div class="grid-2h t-grid-2 m-grid-1h" >
							<h6><a href="{{CROOT}}{{GT8:atendimento.root}}" >Atendimento</a></h6>
							<ul>
								<li><a href="{{CROOT}}{{GT8:atendimento.root}}duvidas-frequentes/" >Dúvidas Frequentes</a></li>
								<li><a href="{{CROOT}}{{GT8:atendimento.root}}duvidas-frequentes/" >Dúvidas Frequentes</a></li>
								<li><a href="{{CROOT}}{{GT8:atendimento.root}}trocas-e-devolucoes/" >Trocas e Devoluções</a></li>
								<li><a href="{{CROOT}}{{GT8:atendimento.root}}prazos-de-entrega/" >Entregas</a></li>
								<li><a href="{{CROOT}}{{GT8:atendimento.root}}formas-de-pagamento/" >Pagamentos</a></li>
								<li><a href="{{CROOT}}{{GT8:account.root}}" >Meus Cadastro</a></li>
								<li><a href="{{CROOT}}{{GT8:account.root}}{{GT8:account.orders.root}}" >Meus Pedidos</a></li>
							</ul>
						</div>
						<div class="grid-2h t-grid-2 m-grid-1h" >
							<h6><a href="{{CROOT}}institucional/" >Institucional</a></h6>
							<ul>
								<li><a href="{{CROOT}}institucional/sobre-a-empresa/" >Sobre a Empresa</a></li>
								<li><a href="{{CROOT}}institucional/trabalhe-conosco/" >Trabalhe Conosco</a></li>
								<li><a href="{{CROOT}}institucional/politica-de-privacidade/" >Política de Privacidade</a></li>
								<li><a href="{{CROOT}}institucional/politica-de-seguranca/" >Política de Segurança</a></li>
								<li><a href="{{CROOT}}institucional/seja-nosso-fornecedor/" >Seja Nosso Fornecedor</a></li>
							</ul>
						</div>
						<div class="grid-2hm t-grid-3 shadowless mobile-hidden" >
							<h6>Certificados</h6>
							<p class="text-light" ><small>As informações de cadastro e compra são transmitidas de forma segura</small></p>
							<p class="text-light" ><small>Donec gravida posuere arcu. Nulla facilisi. Phasellus imperdiet. Vestibulum at metus. Integer euismod</small></p>
							<p class="text-light" ><small>Testes de segurança são feitos diariamente</small></p>
						</div>
						<div class="grid-1h t-grid-3 shadowless text-align-right overflow-hidden mobile-hidden" >
							<p>
								<img src="{{CROOT}}imgs/icn-certisign.png" alt="[Certificado Certisign]" width="100" height="46" />
							</p>
							<p>
								<img src="{{CROOT}}imgs/icn-ebit.png" alt="[Certificado de qualidade]" width="87" height="95" />
							</p>
							<p>
								<img src="{{CROOT}}imgs/icn-seal.png" alt="[Certificado de segurança]" width="100" height="28" />
							</p>
						</div>
					</div>
					<div class="row-12 fluid-12 clearfix-child mobile-hidden" >
						<hr class="grid-12" />
					</div>
					<div class="row-12 fluid-12 block clearfix-child mobile-hidden" >
						<div class="grid-12" >
							<p class="text-light" >
								<small>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit. Nulla facilisi. Nulla libero. Vivamus pharetra posuere sapien. Nam consectetuer. Sed aliquam, nunc eget euismod ullamcorper, lectus nunc ullamcorper orci, fermentum bibendum enim nibh eget ipsum. Donec porttitor ligula eu dolor. Maecenas vitae nulla consequat libero cursus venenatis. Nam magna enim, accumsan eu, blandit sed, blandit a, eros.</small>
							</p>
						</div>
					</div>
				</div>
				<div class="row-12 fluid-12 clearfix-child bottom" >
					<p class="grid-12 margin-bottom-none row-1" >
						<small class="text-light" >Fotos meramente ilustrativas l Ofertas válidas enquanto durarem nossos estoques l Vendas sujeitas a análise de dados </small>
					</p>
					<p class="grid-12 row-2" >
						<small>
							<a href="http://www.salaodocalcado.com.br/" >SALÃO DO CALÇADO (C) 2012</a> | Todos os direitos reservados  |  <a href="{{CROOT}}institucional/politica-de-privacidade/" >Privacidade</a>  |  <a href="{{CROOT}}institucional/politica-de-seguranca/" >Segurança</a>  |  <a href="{{CROOT}}{{GT8:atendimento.root}}" >SAC</a>  |  <a href="{{CROOT}}{{GT8:atendimento.root}}contato/" >Contato</a>
						</small>
					</p>
				</div>
			</footer>
