<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>{{title}} | Salão do Calçado</title>
		{{VIEW:head}}
	</head>
	<body class="not-found" >
		<div id="eMain" >
			{{VIEW:header}}
			<div class="height-superlarge" ></div>
			<div class="row-12 cards" >
				<p class="grid-2" >
					<img src="{{CROOT}}imgs/message-large.png" alt="[informativo]" width="128" height="128" />
				</p>
				<h1 class="grid-8" >{{title}},</h1>
				<p class="grid-8" >
					{{message}}
				</p>
				<div class="clearfix" ></div>
			</div>
			{{VIEW:footer}}
		</div>
	</body>
</html>