					<h1>Formas de Pagamento</h1>
					<p>
						Para comodidade do cliente, o <a href="http://www.salaodocalcado.com.br" class="link" >Salão do calcado</a> oferece os métodos mais utilizados de pagamentos existentes no mercado, incluindo cartão de crédito e boleto bancário.
					</p>
					<p>
						Para os pagamentos realizados com cartão de crédito, aceitamos as bandeiras Visa, Master Card, Diners Club e Hypercard. O pagamento poderá ser feito à vista ou em até 3 vezes sem juros. <br /><br />
						A compra realizada com cartão é segura. Todos os dados das transações são encriptografados antes de serem enviados à operadora do cartão. Nenhuma informação relacionada ao cartão é armazenada, de modo que, não importa o que aconteça, seus dados não serão roubados.
					</p>
					<p>
						Pagamentos realizados com boleto bancário podem ser efetuados na agência bancária de sua preferência, pela internet no site do seu banco, ou em estabelecimentos que aceitem boleto bancário.
					</p>