					<li>
						<a href="{{CROOT}}{{GT8:atendimento.root}}duvidas-frequentes/" class="href-button href-button-cancel line-height-large font-size-small text-align-left text-indent margin-bottom-small" >
							<span>Dúvidas Frequentes</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}{{GT8:atendimento.root}}trocas-e-devolucoes/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Trocas e Devoluções</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}{{GT8:atendimento.root}}prazos-de-entrega/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Prazos de Entrega</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}{{GT8:atendimento.root}}formas-de-pagamento/" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Formas de Pagamento</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}{{GT8:account.root}}{{GT8:account.orders.root}}" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Meus Pedidos</span>
						</a>
					</li>
					<li>
						<a href="{{CROOT}}{{GT8:account.root}}" class="href-button href-button-cancel text-align-left text-indent line-height-large font-size-small margin-bottom-small" >
							<span>Meu Cadastro</span>
						</a>
					</li>
