					<h1>Prazos de Entrega</h1>
					<p>
						<a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a>
						
						Prezamos muito você como cliente e, por isso, queremos garantir que seu pedido chegue o mais rápido possível.<br />
						O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> utiliza os Correios ou transportadoras especializadas para a entrega dos produtos.
					</p>
					<p>
						As entregas são feitas de segunda a sexta-feira, das 8:00 às 21:00. O prazo de entrega de uma encomenda varia de acordo com o produto
					</p>
					<p>
						
						Contagem do prazo em dias úteis;

Nossas entregas são realizadas de segunda a sexta feira das 8h às 21h;

O prazo de entrega será contado após confirmação dos seus dados cadastrais e confirmação do pagamento, sendo que a análise de dados cadastrais poderá levar até um dia útil;

Para pagamento em Boleto bancário, o banco poderá levar até dois dias úteis para comunicar a Dafiti no processo de compensação bancária; Será considerado o horário da aprovação do pagamento e não o momento da sua compra. Por exemplo, se você comprou em 01/12/2011 (quinta feira) às 12h, seu pagamento foi aprovado em 02/12/2011 (sexta feira) às 07h e seu prazo de entrega são 3 dias úteis, a sua data prevista para entrega é 07/12/2011 (quarta feira);

O serviço de entrega é realizado por meio dos Correios ou Transportadoras contratadas pela Dafiti;

A entrega poderá ser feita a terceiros, como porteiros ou parentes;

Após emissão de sua Nota Fiscal não é possível fazer qualquer alteração no endereço informado para entrega;

					</p>
					
					
					
					Você merece comprar com o máximo de conforto, e segurança. Por isso não medimos esforços para garantir que o seu pedido chegue o quanto antes. 

O prazo para entrega dos produtos varia de acordo com o local, a forma de pagamento escolhida e a disponibilidade do produto adquirido. Você pode simular o prazo selecionando o item que deseja e clicar no botão “COMPRAR”. Você será direcionado ao carrinho de compras. Basta adicionar o número de seu CEP no campo logo abaixo do produto, e clicar em “CALCULAR”.  Imediatamente aparecerá o prazo de entrega. 

Se você já é nosso cliente e comprou recentemente conosco, pode acompanhar seu pedido já postado clicando aqui.



Para que a expectativa de receber sua compra seja alcançada, calculamos aproximadamente os dias que sua compra levará para chegar ao endereço de entrega. O prazo varia de acordo com o local e o método de entrega no ato da compra, lembrando que o prazo será contato após a data de aprovação do seu pedido pelo departamento de analise.

Você pode acompanhar o Status do seu pedido através do seu cadastro no site, no item meus pedidos e também receberá um e-mail confirmando sua compra e prazo de entrega. 