					<h1>Prazos de Entrega</h1>
					<p>
						Prezamos muito você como cliente e, por isso, queremos garantir que seu pedido chegue o mais rápido possível.<br />
					</p>
					<p>
						O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> utiliza os Correios ou transportadoras especializadas para a entrega dos produtos.
					</p>
					<p>
						As entregas são feitas de segunda a sexta-feira, das 8:00 às 21:00. O prazo de entrega de uma encomenda varia de acordo com o produto, a localização do cliente e o método escolhido para entrega.
					</p>
					<p>
						Para as compras feitas com cartão de crédito, o prazo para entregar será contato a partir da data de aprovação do departamento de análise de crédito. Nas compras pagas através de boleto bancário, a data prevista de entrega será contada a partir da compensação do boleto, que poderá levar até dois dias úteis.
					</p>
					<p>
						E-mails serão automaticamente enviados indicando a situação de sua compra. O <em>status</em> do seu pedido será alterado conforme a situação de seu pedido. Você poderá acompanhar o processo através do link <a href="{{CROOT}}{{GT8:account.root}}{{GT8:account.orders.root}}" class="link" >Meus pedidos</a> a qualquer momento.
					</p>