					<div class="cards" >
						<div class="card grid-8 bg-light shadow-small alpha omega margin-bottom" >
							<div class="padding display-block" >
								<h1>Serviço de Atendimento ao Cliente <br />(11) 3539-2258</h1>
								<p>
									Donec gravida posuere arcu. Nulla facilisi. Phasellus imperdiet. Vestibulum at metus. Integer euismod. Nullam placerat rhoncus sapien. Ut euismod. Praesent libero. Morbi pellentesque libero sit amet ante. Maecenas tellus. Maecenas erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
								</p>
								<p>
									Proin at eros non eros adipiscing mollis. Donec semper turpis sed diam. Sed consequat ligula nec tortor. Integer eget sem. Ut vitae enim eu est vehicula gravida. Morbi ipsum ipsum, porta nec, tempor id, auctor vitae, purus. Pellentesque neque. Nulla luctus erat vitae libero. Integer nec enim. Phasellus aliquam enim et tortor. Quisque aliquet, quam elementum condimentum feugiat, tellus odio consectetuer wisi, vel nonummy sem neque in elit. Curabitur eleifend wisi iaculis ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non velit non ligula laoreet ultrices. Praesent ultricies facilisis nisl. Vivamus luctus elit sit amet mi. Phasellus pellentesque, erat eget elementum volutpat, dolor nisl porta neque, vitae sodales ipsum nibh in ligula. Maecenas mattis pulvinar diam. Curabitur sed leo.
								</p>
								<div class="clearfix" ></div>
							</div>
						</div>
						<a href="{{CROOT}}{{GT8:atendimento.root}}duvidas-frequentes/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/doubts.png" alt="[Ícone]" width="96" height="128" />
								<strong class="display-block margin-bottom-small" >Dúvidas Frequentes</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in felis egestas rutrum.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}trocas-e-devolucoes/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/refounds.png" alt="[Ícone]" width="" height="" />
								<strong class="display-block margin-bottom-small" >Trocas e Devoluções</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}prazos-de-entrega/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/delivery.png" alt="[Ícone]" width="128" height="112" />
								<strong class="display-block margin-bottom-small" >Prazos de Entrega</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in felis egestas rutrum.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}formas-de-pagamento/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/pay.png" alt="[Ícone]" width="128" height="128" />
								<strong class="display-block margin-bottom-small" >Formas de Pagamento</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:account.orders.root}}" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/orders.png" alt="[Ícone]" width="128" height="128" />
								<strong class="display-block margin-bottom-small" >Seus Pedidos</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:account.root}}" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/account.png" alt="[Ícone]" width="104" height="127" />
								<strong class="display-block margin-bottom-small" >Seu Cadastro</strong>
								<span>
									Mauris aliquet mattis metus, Duis dignissim euismod quam. Aliquam sagittis magna in felis egestas rutrum.
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<div class="clearfix" ></div>
					</div>
