					<div class="cards" >
						<div class="card grid-8 bg-light shadow-small alpha omega margin-bottom" >
							<div class="padding display-block" >
								<h1>Serviço de Atendimento ao Cliente <br />(11) 3539-2258</h1>
								<p>
									O canal de atendimento <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> poderá lhe esclarecer dúvidas relacionadas ao processo de compras, acompanhamento de pedidos e cadastro.
								</p>
								<p>
									Desejamos que você faça ótimas compras e estamos à disposição para lhe ajudar.
								</p>
							</div>
						</div>
						<a href="{{CROOT}}{{GT8:atendimento.root}}duvidas-frequentes/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/doubts.png" alt="[Ícone]" width="96" height="128" />
								<strong class="display-block margin-bottom-small" >Dúvidas Frequentes</strong>
								<span>
									Consulte aqui a lista de perguntas e respostas mais comuns
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}trocas-e-devolucoes/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/refounds.png" alt="[Ícone]" width="" height="" />
								<strong class="display-block margin-bottom-small" >Trocas e Devoluções</strong>
								<span>
									Saiba como solicitar troca ou devolução do produto
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}prazos-de-entrega/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/delivery.png" alt="[Ícone]" width="128" height="112" />
								<strong class="display-block margin-bottom-small" >Prazos de Entrega</strong>
								<span>
									Saiba das regras usadas para calcular sua entrega
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:atendimento.root}}formas-de-pagamento/" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/pay.png" alt="[Ícone]" width="128" height="128" />
								<strong class="display-block margin-bottom-small" >Formas de Pagamento</strong>
								<span>
									Conheça as formas de pagamento disponíveis
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:account.root}}{{GT8:account.orders.root}}" class="card grid-4 height-2 bg-light shadow-small text-decoration-none alpha margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/orders.png" alt="[Ícone]" width="128" height="128" />
								<strong class="display-block margin-bottom-small" >Seus Pedidos</strong>
								<span>
									Clique aqui para ver informações de seus pedidos
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<a href="{{CROOT}}{{GT8:account.root}}" class="card grid-4 height-2 bg-light shadow-small text-decoration-none omega margin-bottom" >
							<span class="padding-small display-block" >
								<img class="float-left" src="{{CROOT}}{{GT8:atendimento.root}}imgs/account.png" alt="[Ícone]" width="104" height="127" />
								<strong class="display-block margin-bottom-small" >Seu Cadastro</strong>
								<span>
									Clique aqui para acessar seu cadastro pessoal
								</span>
								<span class="clearfix" >&nbsp;</span>
							</span>
						</a>
						<div class="clearfix" ></div>
					</div>
