					<h1>Trocas de Devoluções</h1>
					<p>
						O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> existe por sua causa. Portanto, preocupamos em lhe oferecer um ótimo atendimento, com política de troca e devolução que lhe garanta satisfação.
					</p>
					
					<h3 class="margin-bottom-none" >Troca por modelo ou numeração diferente</h3>
					<p>
						Após o recebimento do produto, a solicitação de troca poderá ser feita em até 7 dias corridos, pela <a href="{{CROOT}}{{GT8:atendimento.root}}" class="link" >Central de atendimento</a>.<br />
						Por cortesia do <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a>, os custos oriundos do transporte da primeira troca serão custeados pelo <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a>.
					</p>
 
					<h3 class="margin-bottom-none" >Produtos com defeito</h3>
					<p>
						Entre em contato conosco através da <a href="{{CROOT}}{{GT8:atendimento.root}}" class="link" >Central de atendimento</a> e relate o defeito apresentado. A solicitação poderá ser feita até 30 dias corridos, contatos a partir do recebimento do produto. O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> custeará as despesas oriundas do transporte.
					</p>
 
					<h3 class="margin-bottom-none" >Condições de troca e devolução</h3>
					<p>
						O produto deverá ser devolvido sem uso, em sua embalagem original, acompanhada da nota fiscal, sem indícios de uso ou dano intencionais.
					</p>
 
					<h3 class="margin-bottom-none" >Restituição do produto em caso de troca</h3>
					<p>
						Após postagem do produto por parte do cliente e o recebimento do mesmo em nossos departamentos, será despachado o produto solicitado no próximo dia útil, se houver disponível em estoque. Em caso de indisponibilidade, o cliente será notificado sobre o prazo necessário para o envio do produto solicitado.
					</p>
 
					<h3 class="margin-bottom-none" >Restituição dos valores em caso de devolução ou desistência</h3>
					<p>
						Se o cliente se qualificar para a desistência, conforme previsto no <a href="http://www.planalto.gov.br/ccivil_03/Leis/L8078compilado.htm" >código de defesa do consumidor</a>,
						assim que for confirmado o recebimento do produto por nossa logística, a restituição do pagamento poderá ocorrer das seguintes formas:
					</p>
					<p>
						Se a compra do produto foi mediante cartão de crédito, será estornado o valor conforme o procedimento adotado da administradora do seu cartão de Ωcrédito.
						O <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a> não tem autonomia sobre as diretrizes adotadas pela Administradora do cartão de crédito
					</p>
					<p>
						Para as compras pagas através de boleto bancário e transferência online, a restituição será feita por meio de débito na conta corrente do titular da compra no prazo máximo de 5 dias úteis.
						Caso o cliente não possua conta em banco, uma Ordem de Pagamento será realizada.
					</p>
					<p>
						Em caso de dúvidas, estamos sempre dispostos a lhe atender da melhor forma possível.<br />Equipe <a href="http://www.salaodocalcado.com.br" class="link" >Salãodocalcado.com.br</a>.
					</p>