<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Permissão negada</title>
		{{VIEW:head}}
	</head>
	<body>
		<div id="eMain" >
			{{VIEW:header}}
			<div class="wrapper" >
				<div class="row padding-top" >
					<h2 class="block" >Você não tem permissão para acessar este diretório!</h2>
					<div class="block" >
						<small class="text-error" >"{{path}}"</small> 
					</div>
					<p class="block" >
						Se realmente precisa acesssar este arquivo, por favor, contate o administrador do sistema.
					</p>
					<div class="clear" ></div>
				</div>
			</div>
			{{VIEW:footer}}
		</div>
	</body>
</html>