				<div id="eCartLocation" class="grid-6" >
					<img id="eLocationImg" src="{{CROOT}}imgs/gt8/blank.gif" usemap="#eLocationImg" width="442" height="42" alt="" class="float-right" />
					<map name="eLocationImg">
						<area shape="rect" coords="0,0,112,40" href="{{CROOT}}{{GT8:cart.root}}" alt="Sacola" title="Sacola"    />
						<area shape="rect" coords="112,0,222,40" href="{{CROOT}}{{GT8:cart.root}}entrega/" alt="Entrega" title="Entrega"    />
					</map>
				</div>
